export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ARTICLE_LIST_SWITCH = 'ARTICLE_LIST_SWITCH'
export const SCROLLDATA = 'SCROLLDATA'

// USER
export const USER__VUEX_FOLLOW = 'USER__VUEX_FOLLOW'
export const USER__VUEX_FOLLOW_PENDING = 'USER__VUEX_FOLLOW_PENDING'
export const USER__VUEX_LOGIN = 'USER__VUEX_lOGIN'
export const USER__VUEX_LOGIN_INFO = 'USER__VUEX_lOGIN_INFO'